'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { api } from '@/lib/api-client';
import { Card, DemoTag, PageHeader, SeverityBadge, Spinner, StatusBadge, Tag } from '@/components/ui';

interface ReportDoc {
  title: string; type: string; summary: string; isDemo: boolean; verificationStatus: string;
  createdAt: string; generatedBy?: { name: string };
  project?: { name: string; website: string; isDemo: boolean };
  sections: Record<string, unknown> & {
    executiveSummary?: { findingsTotal: number; critical: number; tasksCompleted: number; tasksFailed: number; agentRuns: number; aiNarrative?: { text: string; aiGenerated: boolean; provider: string; model: string } | null; byStatus?: Record<string, number> };
    workCompleted?: { title: string; kind: string }[];
    problemsDiscovered?: { title: string; severity: string; status: string; url?: string; verification: string }[];
    pendingWork?: { title: string; status: string; priority: string }[];
    verificationStatus?: { verified: number; failed: number; notVerified: number };
    nextPriorities?: { title: string; severity: string; internalPriorityScore: number; recommendedAction?: string }[];
    performanceData?: { available: boolean; note: string };
  };
}

function Section({ title, children, count }: { title: string; children: React.ReactNode; count?: number }) {
  return (
    <Card>
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-extrabold" style={{ color: 'var(--text)' }}>{title}</h3>
        {count !== undefined && <Tag>{count}</Tag>}
      </div>
      {children}
    </Card>
  );
}

const LIFECYCLE = ['Detected', 'Recommended', 'Approved', 'Executed', 'Verified'];

export default function ReportDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [r, setR] = useState<ReportDoc | null>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    api<ReportDoc>(`/api/reports/${id}`).then(setR).catch((e) => setError(e.message));
  }, [id]);

  if (error) return <Card>{error}</Card>;
  if (!r) return <div className="grid h-[60vh] place-items-center"><Spinner /></div>;
  const es = r.sections.executiveSummary;
  const vs = r.sections.verificationStatus;

  return (
    <div className="mx-auto max-w-[900px]">
      <PageHeader
        title={<span className="flex items-center gap-3">{r.title} {r.isDemo && <DemoTag />}</span>}
        subtitle={`${r.project?.name ?? ''} · Generated by ${r.generatedBy?.name ?? 'Team Head'} · ${new Date(r.createdAt).toLocaleString()}`}
      />

      {/* Lifecycle strip */}
      <Card className="mb-5">
        <div className="flex flex-wrap items-center gap-2">
          {LIFECYCLE.map((s, i) => (
            <div key={s} className="flex items-center gap-2">
              <div className="flex items-center gap-2 rounded-lg border px-3 py-2" style={{ borderColor: 'var(--border)' }}>
                <span className="text-xs font-bold" style={{ color: 'var(--text-2)' }}>{s}</span>
                <span className="text-sm font-extrabold" style={{ color: 'var(--accent)' }}>
                  {s === 'Verified' ? (vs?.verified ?? 0) : (es?.byStatus?.[s] ?? 0)}
                </span>
              </div>
              {i < LIFECYCLE.length - 1 && <span style={{ color: 'var(--text-3)' }}>→</span>}
            </div>
          ))}
          <span className="ml-auto text-[11px]" style={{ color: 'var(--text-3)' }}>{r.verificationStatus}</span>
        </div>
      </Card>

      <div className="space-y-5">
        <Section title="Executive Summary">
          <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
            <div className="rounded-lg border p-3 text-center" style={{ borderColor: 'var(--border)' }}><div className="text-xl font-extrabold" style={{ color: 'var(--text)' }}>{es?.findingsTotal ?? 0}</div><div className="text-[11px]" style={{ color: 'var(--text-2)' }}>Findings</div></div>
            <div className="rounded-lg border p-3 text-center" style={{ borderColor: 'var(--border)' }}><div className="text-xl font-extrabold" style={{ color: '#dc2626' }}>{es?.critical ?? 0}</div><div className="text-[11px]" style={{ color: 'var(--text-2)' }}>Critical</div></div>
            <div className="rounded-lg border p-3 text-center" style={{ borderColor: 'var(--border)' }}><div className="text-xl font-extrabold" style={{ color: '#059669' }}>{es?.tasksCompleted ?? 0}</div><div className="text-[11px]" style={{ color: 'var(--text-2)' }}>Tasks completed</div></div>
            <div className="rounded-lg border p-3 text-center" style={{ borderColor: 'var(--border)' }}><div className="text-xl font-extrabold" style={{ color: 'var(--text)' }}>{es?.agentRuns ?? 0}</div><div className="text-[11px]" style={{ color: 'var(--text-2)' }}>Agent runs</div></div>
          </div>
          {es?.aiNarrative ? (
            <div className="mt-3 rounded-lg border p-3" style={{ borderColor: 'var(--border)', background: 'var(--bg-soft)' }}>
              <div className="mb-1 text-[10px] font-bold uppercase" style={{ color: 'var(--accent)' }}>
                AI-generated narrative · {es.aiNarrative.provider}/{es.aiNarrative.model}
              </div>
              <p className="whitespace-pre-wrap text-xs leading-relaxed" style={{ color: 'var(--text-2)' }}>{es.aiNarrative.text}</p>
            </div>
          ) : (
            <p className="mt-3 text-xs" style={{ color: 'var(--text-3)' }}>Summary compiled deterministically from database records. Enable an AI provider to add a narrative layer (clearly labelled when used).</p>
          )}
        </Section>

        <Section title="Work Completed" count={r.sections.workCompleted?.length ?? 0}>
          <ul className="space-y-1.5">
            {(r.sections.workCompleted ?? []).map((w, i) => (
              <li key={i} className="flex items-center gap-2 text-sm" style={{ color: 'var(--text-2)' }}>
                <span style={{ color: '#10b981' }} className="font-extrabold">✓</span> {w.title} <span className="text-[11px]" style={{ color: 'var(--text-3)' }}>({w.kind})</span>
              </li>
            ))}
            {(r.sections.workCompleted ?? []).length === 0 && <li className="text-xs" style={{ color: 'var(--text-3)' }}>—</li>}
          </ul>
        </Section>

        <Section title="Problems Discovered" count={r.sections.problemsDiscovered?.length ?? 0}>
          <div className="max-h-[420px] space-y-1.5 overflow-y-auto">
            {(r.sections.problemsDiscovered ?? []).map((p, i) => (
              <div key={i} className="flex flex-wrap items-center gap-2 rounded-lg border px-3 py-2 text-xs" style={{ borderColor: 'var(--border)' }}>
                <SeverityBadge value={p.severity} />
                <span className="min-w-0 flex-1 font-semibold" style={{ color: 'var(--text)' }}>{p.title}</span>
                <StatusBadge value={p.status} />
                <span style={{ color: p.verification === 'verified' ? '#059669' : 'var(--text-3)' }}>
                  {p.verification === 'verified' ? '✓ verified' : p.verification === 'failed' ? '✗' : 'not verified'}
                </span>
              </div>
            ))}
          </div>
        </Section>

        <div className="grid gap-5 md:grid-cols-2">
          <Section title="Pending Work" count={r.sections.pendingWork?.length ?? 0}>
            <ul className="space-y-1.5">
              {(r.sections.pendingWork ?? []).map((w, i) => (
                <li key={i} className="flex items-center justify-between gap-2 text-xs" style={{ color: 'var(--text-2)' }}>
                  <span>{w.title}</span><StatusBadge value={w.status} />
                </li>
              ))}
              {(r.sections.pendingWork ?? []).length === 0 && <li className="text-xs" style={{ color: 'var(--text-3)' }}>All caught up.</li>}
            </ul>
          </Section>
          <Section title="Performance Data">
            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-2)' }}>
              {r.sections.performanceData?.note ?? 'Data unavailable.'}
            </p>
            <Tag>Integration required — no metrics fabricated</Tag>
          </Section>
        </div>

        <Section title="Next Priorities" count={r.sections.nextPriorities?.length ?? 0}>
          <ul className="space-y-2">
            {(r.sections.nextPriorities ?? []).map((p, i) => (
              <li key={i} className="flex flex-wrap items-center gap-2 text-xs">
                <span className="grid h-5 w-8 place-items-center rounded-md text-[11px] font-extrabold" style={{ background: 'var(--accent-soft)', color: 'var(--accent)' }}>{p.internalPriorityScore}</span>
                <SeverityBadge value={p.severity} />
                <span className="min-w-0 flex-1 font-semibold" style={{ color: 'var(--text)' }}>{p.title}</span>
                <span className="w-full pl-10 text-[11px]" style={{ color: 'var(--text-3)' }}>{p.recommendedAction}</span>
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[10px]" style={{ color: 'var(--text-3)' }}>Scores are internal work-prioritization scores; they do not predict search rankings.</p>
        </Section>
      </div>
    </div>
  );
}
