'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api-client';
import { Card, DemoTag, EmptyState, PageHeader, Spinner, Tag, timeAgo } from '@/components/ui';

interface Report { _id: string; title: string; type: string; summary?: string; verificationStatus?: string; createdAt: string; isDemo: boolean; project?: { name: string; isDemo: boolean } }

export default function ReportsPage() {
  const [items, setItems] = useState<Report[] | null>(null);
  useEffect(() => {
    api<{ items: Report[] }>('/api/reports').then((d) => setItems(d.items)).catch(() => setItems([]));
  }, []);

  return (
    <div>
      <PageHeader title="Reports" subtitle="Professional, evidence-linked deliverables generated by the Team Head." />
      {!items ? <div className="grid h-40 place-items-center"><Spinner /></div> : items.length === 0 ? (
        <EmptyState title="No reports yet" hint="Complete a project discovery — the Team Head compiles the verified report with a clear Detected → Verified breakdown." />
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {items.map((r) => (
            <Link key={r._id} href={`/app/reports/${r._id}`}>
              <Card className="h-full hover:border-[var(--accent)]">
                <div className="mb-2 flex items-center justify-between gap-2">
                  <Tag tone="blue">{r.type} report</Tag>
                  <span className="text-[11px]" style={{ color: 'var(--text-3)' }}>{timeAgo(r.createdAt)}</span>
                </div>
                <h3 className="font-extrabold leading-snug" style={{ color: 'var(--text)' }}>{r.title}</h3>
                <p className="mt-1.5 text-xs leading-relaxed" style={{ color: 'var(--text-2)' }}>{r.summary}</p>
                <div className="mt-3 flex items-center gap-2 text-[11px]" style={{ color: 'var(--text-3)' }}>
                  {r.project?.name} {(r.isDemo || r.project?.isDemo) && <DemoTag />}
                  {r.verificationStatus && <span className="ml-auto font-bold" style={{ color: '#059669' }}>{r.verificationStatus}</span>}
                </div>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
